name: Build and Deploy code

on: [push, pull_request] 

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    runs-on: self-hosted
    outputs:
      sha_short: ${{ steps.sha_short.outputs.sha_short }}
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get git SHA short
        id: sha_short
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Print git SHA short
        id: print_short
        run: echo ${{ steps.sha_short.outputs.sha_short }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/langchain-chatbot:sha-${{ steps.sha_short.outputs.sha_short }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  deploy:
    runs-on: self-hosted
    needs: [build]
    env:
      sha_short: ${{ needs.build.outputs.sha_short}}
    steps:
      - name: Run Application container in Docker. 
        run: |
         docker run -d -p 7860:7860 -e PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }} -e GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }} ${{ secrets.DOCKER_HUB_USERNAME }}/langchain-chatbot:sha-$${{ env.sha_short }}
    